<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Settings\UserSettings $userSettings
 */

$translate = $this->plugin('translate');
?>

<div class="meta-group guest-profile">
    <h4><?= $translate('Guest profile') ?></h4>
    <div class="value guest-profile">
        <div>
            <?= sprintf($translate('Research subject: %s'), $userSettings->get('guestprofile_field_research')) ?>
        </div>
    </div>
</div>
