<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Entity\User $user
 * @var \Omeka\Settings\UserSettings $userSettings
 */

$translate = $this->plugin('translate');
?>

<div class="property guest-profile">
    <h4><?= $translate('Guest profile') ?></h4>
    <div class="value guest-profile">
        <ul class="guest-profile">
            <li>
                <?= sprintf($translate('Research subject: %s'), $userSettings->get('guestprofile_field_research')) ?>
            </li>
        </ul>
    </div>
</div>
